config/routes.rb
Rails.application.routes.draw do
  resources :issues do
    Issue::STATUSES.each do |status|
      patch status, on: :member
    end
  end

  root to: 'issues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord

  STATUSES = [PENDING = 'pending', DOING = 'doing', CLOSED = 'closed']

  attr_accessor :request_ip

  after_initialize :set_status

  after_create_commit { IssueBroadcastJob.perform_later self, 'create' }
  after_update_commit { IssueBroadcastJob.perform_later self, 'update' }
  after_destroy { IssueBroadcastJob.perform_later self, 'delete' }

  validates :name, :status, presence: true
  validates :status, inclusion: { in: STATUSES }

  belongs_to :subtask

  def change_status!(a_status)
    update! status: a_status
  end

  def label
    case status
    when PENDING then 'warning'
    when DOING then 'info'
    when CLOSED then 'success'
    end
  end

  private

  def set_status
    self.status ||= PENDING
  end

end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task
  has_many :issues

  alias_attribute :to_s, :name
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :subtasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  load_resource

  def index
  end

  def show
  end

  def new
  end

  def create
    @issue = Issue.new issue_params
    @issue.save!
    redirect_to issues_path, notice: t("issue.create", name: @issue.name)
  end

  def edit
  end

  def update
    @issue.update! issue_params
    render nothing: true
  end

  def destroy
    @issue.destroy
    render nothing: true
  end

  Issue::STATUSES.each do |status|
    define_method status do
      @issue.change_status! status
    end
  end

  private

  def issue_params
    params.require(:issue).permit(:name, :status, :subtask_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/application/_notice.html.erb
<div class="alert alert-success">
  <%= message %>
</div>

app/views/issues/_form.html.erb
<%= form_for issue, remote: remote do |f| %>
  <div class="form-body pal">
    <div class="form-group">
      <div class="input-icon">
        <%= fa_icon :comment %>
        <%= f.text_field :name, autofocus: true, placeholder: 'Issue description', class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.select :subtask_id, Subtask.all.map { |subtask| [subtask.name, subtask.id] }, { include_blank: 'Select a subtask' }, { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.select :status, Issue::STATUSES.map { |status| [status.humanize, status] }, { prompt: true }, { class: 'form-control' } %>
    </div>
  </div>
  <div class="form-actions text-right pal">
    <button type="submit" class="btn btn-primary">Continue</button>
  </div>
<% end %>

app/views/issues/_issue.html.erb
<tr id="issue_<%= issue.id %>">
  <td>#<%= issue.id.to_s.rjust(3, '0') %></td>
  <td><%= issue.name %></td>
  <td><%= issue.subtask.name %></td>
  <td>
    <div class="pull-right">
      <%= link_to 'Editar', [:edit, issue], class: 'btn btn-xs btn-info' %>
      <div class="btn-group btn-group-xs">
        <button type="button" data-toggle="dropdown" class="btn btn-xs btn-primary dropdown-toggle">
          Status &nbsp;<span class="caret"></span>
        </button>
        <ul role="menu" class="dropdown-menu">
          <% Issue::STATUSES.each do |status| %>
            <li><%= link_to status.humanize, url_for([status, issue]), method: :patch, remote: true %></li>
          <% end %>
        </ul>
      </div>
      <%= link_to 'Eliminar', issue, data: { method: :delete, remote: true }, class: 'btn btn-xs btn-danger' %>
    </div>
    <span class="label label-sm label-<%= issue.label %>"><%= issue.status %></span>
  </td>
</tr>

app/views/issues/edit.html.erb
<!--BEGIN TITLE & BREADCRUMB PAGE-->
<div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
  <div class="page-header pull-left">
    <div class="page-title">Edit issue #<%= @issue.id %></div>
  </div>
  <div class="clearfix"></div>
</div>
<!--END TITLE & BREADCRUMB PAGE-->

<div id="flash"></div>

<!--BEGIN CONTENT-->
<div class="page-content">
  <%= render 'form', issue: @issue, remote: true %>
</div>

app/views/issues/index.html.erb
<!--BEGIN TITLE & BREADCRUMB PAGE-->
<div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
  <div class="page-header pull-left">
    <div class="page-title">Issues console</div>
  </div>
  <div class="clearfix"></div>
</div>
<!--END TITLE & BREADCRUMB PAGE-->

<div id="flash"></div>

<!--BEGIN CONTENT-->
<div class="page-content">
  <table id="issues" class="table table-hover">
    <thead>
      <tr>
        <th>Number</th>
        <th>Username</th>
        <th>Age</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <%= render @issues %>
    </tbody>
  </table>
</div>
<!--END CONTENT-->

app/views/issues/new.html.erb
<!--BEGIN TITLE & BREADCRUMB PAGE-->
<div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
  <div class="page-header pull-left">
    <div class="page-title">New issue</div>
  </div>
  <div class="clearfix"></div>
</div>
<!--END TITLE & BREADCRUMB PAGE-->

<div id="flash"></div>

<!--BEGIN CONTENT-->
<div class="page-content">
  <%= render 'form', issue: @issue, remote: false %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickets</title>
    <%= tag :meta, charset: 'utf-8' %>
    <%= tag :meta, 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' %>
    <%= tag :meta, name: :viewport, content: "width=device-width, initial-scale=1.0" %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <div>
      <!--BEGIN BACK TO TOP-->
      <a id="totop" href="#"><i class="fa fa-angle-up"></i></a>
      <!--END BACK TO TOP-->

      <!--BEGIN TOPBAR-->
      <div id="header-topbar-option-demo" class="page-header-topbar">
        <nav id="topbar" role="navigation" style="margin-bottom: 0;" data-step="3" class="navbar navbar-default navbar-static-top">
          <div class="navbar-header">
            <button type="button" data-toggle="collapse" data-target=".sidebar-collapse" class="navbar-toggle">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to root_path, class: 'navbar-brand', id: :logo do %>
              <span class="fa fa-rocket"></span>
              <span class="logo-text">Xaver</span>
              <span style="display: none" class="logo-text-icon">µ</span>
            <% end %>
          </div>
          <div class="topbar-main">
            <%= link_to fa_icon(:bars), '#', class: 'hidden-xs', id: 'menu-toggle' %>
          </div>
        </nav>
      </div>
      <!--END TOPBAR-->

      <div id="wrapper">
        <!--BEGIN SIDEBAR MENU-->
        <nav id="sidebar" role="navigation" class="navbar-default navbar-static-side">
          <div class="sidebar-collapse menu-scroll">
            <ul id="side-menu" class="nav">
              <div class="clearfix"></div>
              <li>
                <%= link_to root_path do %>
                  <%= fa_icon :tachometer, class: 'fa-fw' %>
                  <span class="menu-title">Issues</span>
                <% end  %>
              </li>
              <li>
                <%= link_to new_issue_path do %>
                  <%= fa_icon :th, class: 'fa-fw' %>
                  <span class="menu-title">New issue</span>
                <% end  %>
              </li>
            </ul>
          </div>
        </nav>
        <!--END SIDEBAR MENU-->

        <!--BEGIN PAGE WRAPPER-->
        <div id="page-wrapper">
          <%= yield %>
          <!--BEGIN FOOTER-->
          <div id="footer">
            <div class="copyright">
              <%= link_to '2016 © Xaver Soluciones + Tecnología', 'http://www.xaver.com.ar' %>
            </div>
          </div>
          <!--END FOOTER-->
        </div>
        <!--END PAGE WRAPPER-->
      </div>
    </div>

  </body>

</html>